### ISSUE TITLE
ReportController

### ISSUE THREAD

**Issue by lukasbischof** [stiftungswo/better-dime#100]
|Verb|Action|Description|Old (deprecated) action|Note|
|-----|------|------------|-|-|
|GET|employee_effort|Returns a PDF report of an effort||Previously implemented in the EmployeeController|
|GET|invoice|Returns an invoice PDF||Previously implemented in InvoiceController#print
|GET|invoice/esr|Returns an Invoice ESR PDF|| Previously implemented in InvoiceController#print_esr
|GET|invoice/effort|Returns an Effort Report PDF||Previously implemented in InvoiceController#printEffortReport
|GET|offer|Returns an offer PDF||Previously implemented in OfferController#print
|GET|project/effort|Returns an effort PDF||Previously implemented in ProjectController#printEffortReport
|GET|service_hours|Returns a service hour report||
|GET|revenue|Revenue report
|GET|project|Returns a project report
|GET|cost_group|Returns a cost group report

**Comment by stillhart** [comment]
- [ ]  service_hours

**Comment by stillhart** [comment]
- [ ] costgroup

**Comment by stillhart** [comment]
- [ ] revenue
