### ISSUE TITLE
Match rails models/db to laravel models/db

### ISSUE THREAD

**Issue by Gumbee** [stiftungswo/better-dime#182]
- [x] Addresses
- [x] CostGroups
- [x] Customers
- [x] CustomerTaggable
- [x] CustomerTags
- [x] Employees
- [x] EmployeeGroups
- [ ] EmployeeSettings
- [x] GlobalSettings
- [x] Holidays
- [x] Invoices
- [x] InvoiceCostGroupDistributions
- [x] InvoiceDiscounts
- [x] InvoicePositions
- [x] Offers
- [x] OfferDiscounts
- [x] OfferPositions
- [x] Phones
- [x] PositionGroups
- [x] Projects
- [x] ProjectCategories
- [x] ProjectComments
- [x] ProjectCommentPresets
- [x] ProjectCostgroupDistributions
- [x] ProjectEfforts
- [x] ProjectPositions
- [x] RateGroups
- [x] RateUnits
- [x] Services
- [x] ServiceRates
- [x] WorkPeriods
- [x] WhitelistedJwts
- [x] Versions

**Comment by stillhart** [comment]
#183
