### ISSUE TITLE
Add localization to dime

### ISSUE THREAD

**Issue by Gumbee** [stiftungswo/better-dime#222]
add multiple language support to frontend

**Comment by dacin21** [comment]
Im iZivi ist das mit `react-intl` und `babel-plugin-react-intl` gemacht, also würde ich für das dime das Gleiche verwenden.

**Comment by dacin21** [comment]
TODO:
- [ ] Initialize frontend locale with the user's language field.
- [ ] Pass frontend locale back to backend for PDFs.

**Comment by dacin21** [comment]
Done in 87fd30e2fd7612d0ec3aafc5757f4d63b883e12d
