### ISSUE TITLE
Replace a with ¨ (and similar) to form ä (incompatible encodings in the markdown renderer)

### ISSUE THREAD

**Issue by Gumbee** [stiftungswo/better-dime#277]
There was an error a while back where a project could not be saved. The reason turned out to be bacuse there were characters in the description of the project (the description which is rendered using a markdown renderer) which had incompatible encoding. It turns out that somebody wrote ä,ö and ü by combining the characters ¨ with a,o and u instead of using the actual characters for the umlaute. I don't know how whoever did it managed to do that, because on my mac combining ¨ with a,u and o automatically converts the character to ä,ö and ü, (you can test if it converts by deleting the character. if you need to delete the character twice for it to disappear it hasn't converted it).

The solution is either to check for encodings when saving and to report incompatible encoding, or to search the description for these unconverted characters and automatically convert them to äöü.

**Comment by tourn** [comment]
Wahrscheinlich daselbe Problem, mit einem U200B ZERO WIDTH SPACE: https://sentry.io/share/issue/ec247aefee3343a88774898bded49cea/

**Comment by tourn** [comment]
Nach meinem erachten lassen sich zusammengesetzte Charaktere (äöüïë) problemlos speichern - jedoch fällt dann das PDF-Generieren auf die Nase, weil es diese Charaktere nicht zum Windows-1252 Zeichensatz konvertieren kann. Eine andere Lösung wäre, ein TTF Font für die PDFs zu verwenden anstatt die Inputs zu putzen.

**Comment by tourn** [comment]
https://ruby-doc.org/stdlib-2.4.0/libdoc/unicode_normalize/rdoc/String.html#method-i-unicode_normalize-label-Unicode+Normalization
