### ISSUE TITLE
Layout Einzahlungsschein verbessern

### ISSUE THREAD

**Issue by JustinRoseProgrammer** [stiftungswo/better-dime#311]
Reporter: TK

---
Workflow:
?

Ist-Zustand:
Durch Dime gedruckte Einzahlungsscheine schneiden bei "Einzahlung für" den Text links um ca. 3mm ab.
![2020-12-09T12_43_22 739Z](https://user-images.githubusercontent.com/75605996/101632166-c946e680-3a25-11eb-9636-f495b01dc891.jpeg)

Soll-Zustand:
Text unter "Einzahlung für" wird voll angezeigt.

**Comment by ildacheu** [comment]
Dies wäre ja grad eine Möglichkeit auf die Einzahlungsscheine mit QR-Code umzusteigen. #39

**Comment by ildacheu** [comment]
#c154f2973dbc392bfe0cd57ab593188680c3c890
