### ISSUE TITLE
Positionen gruppieren in Offerten / Projekte / Rechnungen

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/better-dime#34]
Reporter: Lukas Geser

---

Bei grösseren Offerten, Projekten und Rechnungen wäre es wünschenswert, wenn man das Dokument in mehrere Teile mit Titeln gliedern könnte. Dann können Services auch mehrfach erfasst werden, jeweils einmal pro Titel und das Dokument könnte insgesamt komplexer sein bzw. grössere Projekte unterstützen.

Das Feature soll zuschaltbar sein, d.h., auf der Offerte / Projekt / Rechnung kann ausgewählt werden, ob man das Titel-Feature nutzen möchte. Falls nein, bleibt die Ansicht wie heute.

Die Zeiterfassung müsste ebenso ergänzt werden, dass überprüft wird, ob das Projekt das Titel-Feature nutzt und wenn ja, dass man zuerst das Projekt, dann der Titel und dann erst die Aktivität auswählen kann.

Die Validierungen müssten so ergänzt werden, dass geprüft wird, dass sicher jede Position in einem Dokument mit Titel-Feature auch ein Titel verlinkt hat.

**Comment by tourn** [comment]
Implementierung soll folgendermassen passieren: (Im folgenden wird "Offer" verwendet, dasselbe soll aber analog für Project/Invoice passieren)

Neue Tabelle offer_position_group mit Feldern `id`, `offer_id`, `name`

Offer-Positionen können optional auf eine dieser Gruppen verweisen.

Das Backend stöpselt die Informationen so zusammen:

```js
{
  offer_id: 123,
  //...
  position_groups: [
    group_id: 44,
    name: "Bachbett",
    positions: [
      //the positions as before
    ]
  ],
}
```

Man könnte (sollte?) an diesem Punkt die Offer-Positions von der Offer loslösen und die Beziehung nur noch über die neue Group machen.

Im Frontend kann mittels Toggle das neue Feature aktiviert werden:

Mit einem Button können neue Positions-Gruppen erstellt werden. Der Name dieser Gruppen kann verändert werden.

Zusätzlich kann man die Offer-Positionen in einem Collapsible rendern, damit man sie zuklappen kann.
