### ISSUE TITLE
long addresses spread over two pages

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/better-dime#434]
Reporter: Lukas Geser

---

Wenn die Adresse zu lange ist, wird diese beim generieren des PDFs z.B. beim generieren einer Rechnung auf zwei Seiten verteilt.

**Comment by dacin21** [comment]
Repro: [Rechnung_1262_Gemeinde_2021_13_09.pdf](https://github.com/stiftungswo/better-dime/files/7160418/Rechnung_1262_Gemeinde_2021_13_09.pdf)

Relevante Teile des Codes: https://github.com/stiftungswo/better-dime/blob/cef70d27188b04613b62eeee7ec38d3495d91c71/apir/app/services/pdfs/generators/mail_header_generator.rb#L131-L141

Adresse zu lange → Adresse line wrapped → zu viele Adresszeilen → passt nicht in die `bounding_box` → landet auf der nächsten Seite.

Das line-wrapping an sich ist bereits ein Problem. Wenn man z.B. nur die `bounding_box` grösser macht, dann bleibt zwar alles auf einer Seite, ist aber keine gültige Postadresse mehr. Wahrscheinlich sollte man `text_box` verwenden, damit kein line-wrapping passiert.
