### ISSUE TITLE
Changes of the date of the invoice dont show up in the generated pdf of the invoice

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/better-dime#435]
Reporter: Andreas Wolf

---

Wenn das Datum der Rechnung geändert und gespeichert wird, wird im generierten PDF der Rechnung immer noch das alte Datum angezeigt.

**Comment by dacin21** [comment]
Repro:

Wenn man bei `/invoices/<id>` das Ausstellungsdatum ändert, die Rechnung speichert und dann das PDF generiert, dann stimmt das Ausstellungsdatum. Wenn man aber z.B. mit f5 die Seite neu lädt, dann wird das Ausstellungsdatum zurückgesetzt auf das heutige Datum.

**Comment by dacin21** [comment]
Das Ausstellungsdatum wird gar nicht in der DB gespeichert.
Beim neu laden der Seite wird es immer einfach auf den heutigen Tag gesetzt.

**Comment by dacin21** [comment]
Anscheinend ging es um Startdatum / Enddatum und nicht um das Ausstelldatum.
Dieses wird momentan nur gespeichert, wenn man die Zeitspanne neu lädt.

suggested fix: Wenn man speichert und die Zeitspanne nicht neu geladen hat, dann gibt es eine Warnmeldung (oder ein pop-in, ob man neu laden will?).

**Comment by dacin21** [comment]
Weiteres Problem: Wenn man die Zeitspanne aktualisiert und dann in den Project / Invoice tabs hin und her wechselt, dann wird das alte Datum angezeigt, bis man refresht oder die Seite wechselt.
