### ISSUE TITLE
Screenshots und Featurebeschreibung in der Readme

### ISSUE THREAD

**Issue by alexanderadam** [stiftungswo/better-dime#471]
Es wäre schön wenn Neugierige sich vorher anschauen könnten wie der aktuelle Stand der Applikation ist.
Wenn die Readme mit Screenshots und aufgezählten Features ausgestattet werden könnte wäre dies schön.

Und vermutlich braucht es den Teil unter "Vorbereitung (veraltet)" nicht mehr — oder? :thinking: 

**PS:** Noch besser wäre es natürlich, wenn es eine Demo-Instanz zum Herumklicken gäbe

**Comment by dacin21** [comment]
Im Abschnitt "Entwicklung" könnte man das meiste nuken und einfach auf das Wiki verweisen, einverstanden.

Screenshots wären per se nicht schlecht, aber man müsste schauen, dass in den screenshots keine Kundendaten etc. geleakt werden. Ich schätzen den Nutzen als relativ klein ein, ist also eher low-prio. Könnte evtl. jemand am Endes seines Einsatzes als Zeitfüller machen.

Demo-Instanz ist IMO overkill -- wenn jemand wirklich so grossen Eifer hat, dann man sich ja seine eigene Instanz lokal aufsetzen (insb. sobald das setup im readme richtig beschrieben ist). Nutzen ist relativ klein.

**Comment by alexanderadam** [comment]
> Screenshots wären per se nicht schlecht, aber man müsste schauen, dass in den screenshots keine Kundendaten etc. geleakt werden.

Das sollte auch von Entwicklungsumgebungen machbar sein und zur könnte man die Texte rasch mit den Developer-Tools auch rasch im DOM ändern, oder?

> Ich schätzen den Nutzen als relativ klein ein, ist also eher low-prio.

Natürlich. Der Nutzen ist nur für User hoch, die das Projekt noch nicht kennen und nicht wissen ob es sich lohnt das Projekt anzusehen und/oder zu contributen.

Wenn das Projekt nur intern für die Stiftung relevant ist macht das natürlich keinen Sinn und es hätte trotz der einfachen Umsetzung ganz klar keine Priorität.
Aber auch dann wäre es sicherlich von Vorteil dies so in der README zu dokumentieren.

> wenn jemand wirklich so grossen Eifer hat, dann man sich ja seine eigene Instanz lokal aufsetzen (insb. sobald das setup im readme richtig beschrieben ist).

Wenn man in GitHub nach `timetracker` sucht, [findet man über 3'000 Treffer](https://github.com/search?l=&o=desc&q=Timetracker&s=updated&type=Repositories).
Ich bin mir nicht ganz sicher wie hoch die Wahrscheinlichkeit ist, dass jemand so grossen Eifer hat diese über 3'000 Projekte jeweils auszuchecken und aufzusetzen. :wink: 

Insbesondere, da einige der Projekte bereits Screenshots, Demos und Feature-Listen dokumentiert haben (bspw. [Kimai](https://www.kimai.org/), [activitywatch](https://github.com/ActivityWatch/activitywatch#screenshots), [tockler](https://github.com/MayGo/tockler#screenshots), [crick](https://github.com/TailorDev/crick#crick), [Anuko](https://www.anuko.com/time-tracker/index.htm), [Hackaru](https://github.com/hackaru-app/hackaru#screens) etc.).

Daher wird better-dime bei den meisten Evaluationen natürlich direkt wegfallen. Denn es gibt nur eine oberflächliche Beschreibung, die nur sehr allgemein gehalten ist und keinen Rückschluss zulässt, was es besser oder anders machen sollte als andere Projekte.

Aber wie bereits erwähnt: wenn es ohnehin das Ziel ist keine weiteren Nutzer oder externe Entwickler zu haben, wäre das natürlich zielführend (sollte dann jedoch ebenfalls dokumentiert werden).
