### ISSUE TITLE
Rechnungen: PDF Namen

### ISSUE THREAD

**Issue by dacin21** [stiftungswo/better-dime#558]
Reporter:

Lukas G.

---

Die im dime generierten PDFs heissen irgendwie "print.pdf" / "print_qr_bill.pdf".
Eigentliche sollter der filename folgendes Format haben: `Offerte_663_Bassersdorf_2022_03_24.pdf`

**Comment by dacin21** [comment]
- Bei mir funktioniert es in firefox und edge. Die screenshots von Luki sehen nach Handy aus.
- Es sieht so aus, als hätte Luki die Website `/v2/invoices/1510/print` anstelle der generierten Datei heruntergeladen?

Evl. ein android "feature"? https://stackoverflow.com/questions/45297477/limitations-on-opening-pdf-file-in-android

**Comment by dacin21** [comment]
Luki: Problem tritt auf, wenn man auf dem I-Pad das dokument direkt ins google drive speichert.

**Comment by floerb** [comment]
Kann nicht gefixt werden.
