### ISSUE TITLE
"In Arbeit..." message box behält (unsichtbare) Hitbox.

### ISSUE THREAD

**Issue by dacin21** [stiftungswo/better-dime#565]
Reporter:

Daniel R.

(Eher low prio, aber vielleicht findet jemand einen einfachen fix.)

---

Repro:
1) Offerte speichern.
2) "In Arbeit..." > "Die Offerte wurde gespeichert." message box erscheint
3) Message box verschwindet nach einiger Zeit oder durch klicken auf das X.
4) Linke sidebar öffnen, genügend viele Teile aufklappen (z.B. Stammdaten und Rapporte)
5) In der linken-unteren Ecke gibt es nun einen Bereich, in welchem man nicht auf die sidebar klicken kann. Wenn man ausserdem in diesem Bereich versucht zu scrollen, dann scrollt die rechte Seite und nicht die sidebar.

(Bei der Rechnung hat mir das Ganze auch schon mal das drag-n-drop des untersten Aufwands blockiert...)

![grafik](https://user-images.githubusercontent.com/8490534/183871149-f7743c50-f68f-4cf3-afab-8c379f3ee354.png)

**Comment by floerb** [comment]
Will be closed with #569
